---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ecsteam/spring-boot
    tag: '1.5.1.RELEASE'

inputs:
- name: pipeline-source
- name: nozzle-source
- name: version-output

outputs:
- name: build-nozzle-output

run:
  path: pipeline-source/tasks/build-jar/task.sh
