---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ecsteam/spring-boot
    tag: '1.5.1.RELEASE'

inputs:
- name: pipeline-source
- name: nozzle-source

run:
  path: pipeline-source/tasks/run-unit-tests/task.sh
